apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsebcrypt-prod
  namespace: default
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: it022050@hua.gr
    privateKeySecretRef:
      name: account-key-prod
    solvers:
      - http01:
          ingress:
            class: nginx
